CMSHelpLink:
    url: 
GDBackend:
  default_quality: 90
LeftAndMain:
  extra_requirements_css:
    - 'mypswd-tweaks/css/cms.css'
Page:
    extensions:
        - PageHideExtraMetaData
        - PageSettingsHideSearch
        - PageSettingsHidePermissions
Image:
    extensions:
        - ImageFunctions
Member:
    extensions:
        - MemberTidy
LeftAndMain:
    extensions:
        - CMSHelpLink
        - LeftAndMainPageIconsExtension
HtmlEditorField_Toolbar:
    extensions:
        - ImageAlignmentDefaults
ErrorPage:
    extensions:
        - HideErrorPage
VirtualPage:
    extensions:
        - HideVirtualPage
UserDefinedForm:
    extensions:
        - HideUserDefinedForm
BlogHolder:
    extensions:
        - SinglePageOnly